[package]
name = "windows_bindings"
version = "0.1.0"
authors = ["Michael Duerinckx <mich@michd.me>"]
edition = "2018"

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.8.0"

[target.'cfg(target_os = "windows")'.build-dependencies]
windows = "0.8.0"
